const express = require('express');
const cors = require('cors');
const helmet = require('helmet');
const morgan = require('morgan');
require('../database/db');
const log = require('./services/logService');
const { backupExcel } = require('./services/excelService');
const app = express();
app.use(helmet({ contentSecurityPolicy: false }));
app.use(cors());
app.use(express.json({ limit: '20mb' }));
app.use(morgan('dev'));
app.get('/health', (_, res) => res.json({ ok: true, app: 'GarmentPro ERP' }));
app.use('/api/auth', require('./routes/auth'));
app.use('/api/dashboard', require('./routes/dashboard'));
app.use('/api/billing', require('./routes/billing'));
app.use('/api/data', require('./routes/crud'));
app.use('/api/export', require('./routes/importExport'));
app.use((err, req, res, next) => { log.error(err.message, { stack: err.stack }); res.status(500).json({ error: 'GarmentPro ERP handled an unexpected error safely.' }); });
setInterval(() => backupExcel().then(file => log.info('Automatic Excel backup created', { file })).catch(e => log.error(e.message)), 1000 * 60 * 30);
const port = process.env.PORT || 4521;
app.listen(port, () => log.info(`GarmentPro ERP API running on ${port}`));
