import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { AnimatePresence, motion } from 'framer-motion';
import { BarChart3, Boxes, Building2, CalendarCheck, Factory, FileText, Home, Lock, Moon, Package, Search, Settings, Shirt, Sun, Users, WalletCards } from 'lucide-react';
import { Area, AreaChart, Bar, BarChart, CartesianGrid, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { request, setToken, dataApi } from './api';
import './styles/app.css';

const nav = [
  ['dashboard','Dashboard',Home], ['billing','Billing',FileText], ['inventory','Inventory',Boxes], ['production','Production',Factory], ['customers','Customers',Users], ['suppliers','Suppliers',Building2], ['employees','Workers',CalendarCheck], ['reports','Reports',BarChart3], ['admin','Admin',Settings], ['guide','User Guide',Shirt]
];
const modules = { customers:'customers', suppliers:'suppliers', inventory:'products', employees:'employees', production:'production_jobs' };
function money(v){ return new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(v||0); }
function Login({onLogin}) {
  const [form,setForm]=useState({email:'admin@garmentpro.local',password:'admin123'}), [err,setErr]=useState('');
  async function submit(e){ e.preventDefault(); try{ const data=await request('/auth/login',{method:'POST',body:form}); setToken(data.token); onLogin(data.user); }catch(ex){ setErr(ex.message); } }
  return <div className="login"><motion.form initial={{opacity:0,y:20}} animate={{opacity:1,y:0}} onSubmit={submit} className="login-card"><div className="brand"><span>GP</span><div><h1>GarmentPro ERP</h1><p>Premium garment billing & factory management</p></div></div><label>Email<input value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label><label>Password<input type="password" value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/></label>{err&&<b className="error">{err}</b>}<button><Lock size={18}/> Secure Login</button><small>Demo: admin@garmentpro.local / admin123</small></motion.form></div>;
}
function App(){ const [user,setUser]=useState(localStorage.gpe_token?{name:'Admin User',role:'admin'}:null), [page,setPage]=useState('dashboard'), [dark,setDark]=useState(true), [query,setQuery]=useState(''); useEffect(()=>window.garmentPro?.onShortcut(k=>{ if(k==='billing')setPage('billing'); if(k==='search')document.querySelector('#globalSearch')?.focus(); }),[]); if(!user)return <Login onLogin={setUser}/>; return <div className={dark?'app dark':'app'}><aside><div className="logo"><span>GP</span><div><b>GarmentPro ERP</b><small>Enterprise Desktop</small></div></div>{nav.map(([id,label,Icon])=><button key={id} onClick={()=>setPage(id)} className={page===id?'active':''}><Icon size={19}/>{label}</button>)}</aside><main><header><div><h2>{nav.find(n=>n[0]===page)?.[1]}</h2><p>Simple workflow for garment shops, manufacturers, exporters and distributors.</p></div><div className="tools"><div className="search"><Search size={17}/><input id="globalSearch" placeholder="Search products, customers, invoices..." value={query} onChange={e=>setQuery(e.target.value)}/></div><button onClick={()=>setDark(!dark)}>{dark?<Sun/>:<Moon/>}</button><div className="avatar">{user.name?.[0]||'A'}</div></div></header><AnimatePresence mode="wait"><motion.section key={page} initial={{opacity:0,y:12}} animate={{opacity:1,y:0}} exit={{opacity:0,y:-12}}>{page==='dashboard'&&<Dashboard/>}{page==='billing'&&<Billing/>}{modules[page]&&<DataModule table={modules[page]} title={nav.find(n=>n[0]===page)[1]} q={query}/>} {page==='reports'&&<Reports/>}{page==='admin'&&<Admin/>}{page==='guide'&&<Guide/>}</motion.section></AnimatePresence></main></div>; }
function Dashboard(){ const [d,setD]=useState(null); useEffect(()=>{request('/dashboard').then(setD)},[]); if(!d)return <div className="loader">Loading GarmentPro analytics...</div>; const cards=[['Total Sales',money(d.totalSales),WalletCards],['Total Orders',d.totalOrders,FileText],['Pending Payments',money(d.pendingPayments),Users],['Monthly Profit',money(d.monthlyProfit),BarChart3]]; return <><div className="cards">{cards.map(([l,v,I])=><div className="card" key={l}><I/><span>{l}</span><b>{v}</b></div>)}</div><div className="grid two"><Panel title="Sales Trend"><ResponsiveContainer height={260}><AreaChart data={d.monthly}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="month"/><YAxis/><Tooltip/><Area dataKey="sales" stroke="#38bdf8" fill="#38bdf855"/></AreaChart></ResponsiveContainer></Panel><Panel title="Production Status"><ResponsiveContainer height={260}><BarChart data={d.production}><XAxis dataKey="stage"/><YAxis/><Tooltip/><Bar dataKey="target" fill="#6366f1"/><Bar dataKey="completed" fill="#22c55e"/></BarChart></ResponsiveContainer></Panel></div><div className="grid three"><List title="Low Stock Alerts" rows={d.lowStock} cols={['name','stock','low_stock']}/><List title="Top Selling Products" rows={d.topProducts} cols={['name','qty']}/><List title="Worker Performance" rows={d.workers} cols={['name','role','performance_score']}/></div></>; }
function Billing(){ const [products,setProducts]=useState([]),[customers,setCustomers]=useState([]),[items,setItems]=useState([]),[invoice,setInvoice]=useState(null); useEffect(()=>{dataApi('products').list().then(setProducts);dataApi('customers').list().then(setCustomers)},[]); const total=items.reduce((s,i)=>s+i.quantity*i.price*(1+(i.tax_rate||0)/100),0); const add=p=>setItems([...items,{product_id:p.id,description:p.name,quantity:1,price:p.sale_price,tax_rate:5}]); async function create(){ const inv=await request('/billing/invoice',{method:'POST',body:{customer_id:customers[0]?.id,items,paid:total,payment_method:'UPI'}}); setInvoice(inv); } return <div className="billing"><Panel title="Fast Billing (Ctrl+B)"><div className="product-pills">{products.map(p=><button key={p.id} onClick={()=>add(p)}>{p.name}<small>{p.size}/{p.color} · {money(p.sale_price)}</small></button>)}</div><table><tbody>{items.map((i,idx)=><tr key={idx}><td>{i.description}</td><td><input type="number" value={i.quantity} onChange={e=>setItems(items.map((x,n)=>n===idx?{...x,quantity:+e.target.value}:x))}/></td><td>{money(i.price)}</td><td>{i.tax_rate}% GST</td></tr>)}</tbody></table><div className="checkout"><b>Total {money(total)}</b><button disabled={!items.length} onClick={create}>Generate Smart Invoice</button></div></Panel><Panel title="Beautiful Invoice Preview"><div className="invoice"><h2>GarmentPro ERP</h2><p>GST Invoice • Thermal/PDF Ready • QR Enabled</p>{invoice?<><b>{invoice.invoice_no}</b><h1>{money(invoice.total)}</h1><img src={invoice.qr}/><p>Status: {invoice.status}</p></>:<p>Add items to preview invoice instantly.</p>}</div></Panel></div>; }
function DataModule({table,title,q}){ const [rows,setRows]=useState([]),[form,setForm]=useState({}); const api=useMemo(()=>dataApi(table),[table]); useEffect(()=>{api.list(q).then(setRows)},[table,q]); const fields={products:['name','sku','category','size','color','fabric','sale_price','stock','low_stock'],customers:['name','phone','email','gstin','credit_balance'],suppliers:['name','phone','email','gstin','balance'],employees:['name','phone','role','shift','salary','attendance_status','performance_score'],production_jobs:['order_no','stage','target_qty','completed_qty','status','due_date']}[table]; async function save(){ await api.create(form); setForm({}); setRows(await api.list(q)); } return <div className="grid module"><Panel title={`Add ${title}`}>{fields.map(f=><input key={f} placeholder={f.replaceAll('_',' ')} value={form[f]||''} onChange={e=>setForm({...form,[f]:e.target.value})}/>)}<button onClick={save}>Save Record</button></Panel><Panel title={`${title} Records`}><div className="table-wrap"><table><thead><tr>{fields.map(f=><th key={f}>{f}</th>)}</tr></thead><tbody>{rows.map(r=><tr key={r.id}>{fields.map(f=><td key={f}>{r[f]}</td>)}</tr>)}</tbody></table></div></Panel></div>; }
function Reports(){ return <div className="grid three"><ExportCard type="excel" label="Complete Excel Workbook"/><ExportCard type="xml/all" label="XML Backup"/><ExportCard type="csv/products" label="Inventory CSV"/></div>; }
function ExportCard({type,label}){ const [file,setFile]=useState(''); return <Panel title={label}><p>One-click export for auditors, GST reports, accountants and factory owners.</p><button onClick={()=>request(`/export/${type}`).then(r=>setFile(r.file))}>Export</button>{file&&<small>{file}</small>}</Panel>; }
function Admin(){ return <div className="grid two"><Panel title="Security & Roles"><p>Admin authentication, encrypted passwords, JWT sessions, role-ready API permissions and local offline storage.</p></Panel><Panel title="Backup & Restore"><button onClick={()=>request('/export/excel/backup',{method:'POST'}).then(r=>alert(`Backup created: ${r.file}`))}>Create Excel Backup Now</button><div className="drop">Drag & drop XML/Excel files here for guided restore</div></Panel></div>; }
function Guide(){ return <Panel title="GarmentPro ERP User Guide"><ol><li>Login with the admin account and seed demo data.</li><li>Use Billing for fastest invoice creation with GST, QR and PDF output.</li><li>Manage SKU, size, color, fabric, warehouse and low-stock alerts in Inventory.</li><li>Track cutting, stitching, finishing and packing in Production.</li><li>Export Excel/XML/PDF reports from Reports and schedule backups from Admin.</li></ol><p>Keyboard shortcuts: Ctrl+B billing, Ctrl+F search, Ctrl+I invoice workflow.</p></Panel>; }
function Panel({title,children}){ return <div className="panel"><h3>{title}</h3>{children}</div>; }
function List({title,rows,cols}){ return <Panel title={title}><table><tbody>{rows.map((r,i)=><tr key={i}>{cols.map(c=><td key={c}>{r[c]}</td>)}</tr>)}</tbody></table></Panel>; }
createRoot(document.getElementById('root')).render(<App/>);
